# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Homework23_PicturesRepository' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework23_PicturesRepository

pod 'SwiftyKeychainKit', '1.0.0-beta.2'

  target 'Homework23_PicturesRepositoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Homework23_PicturesRepositoryUITests' do
    # Pods for testing
  end

end
